// Lektion 1
List<String> lektion1 = [
  'silentium',
  'esse',
  'asinus',
  'non iam',
  'clamare',
  'etiam',
  'tacere',
  'villa',
  'iacere',
  'porta',
  'patere',
  'stare',
  'et',
  'exspectare',
  'sic',
  'cogitare',
  'ubi?',
  'cur?',
  'amica',
  'non',
  'venire',
  'properare',
  'placere',
  '(non) placet',
  'subito',
  'valde',
  'gaudere',
  'quid? ',
  'ecce!',
  'quis?'
];



List<String> lektion1Exp = [
  'n',
  '',
  'm',
  '',
  'clamo',
  '',
  '',
  'f',
  '',
  'f',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'f',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''
];

List<String> lektion1ExpPPP = [
  'n',
  '',
  'm',
  '',
  'clamo clamavi clamatum',
  '',
  '',
  'f',
  '',
  'f',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'f',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''
];
List<String> lektion1De = [
  'die Ruhe',
  'sein',
  'der Esel',
  'nicht mehr',
  'schreien',
  'auch; sogar',
  'schweigen',
  'das (Land-)Haus',
  '(da)liegen',
  'das Tor, die Tür',
  'offen stehen',
  '(da) stehen',
  'und; auch',
  'warten (auf)',
  'so',
  'denken; nachdenken; beabsichtigen',
  'wo?',
  'warum?',
  'die Freundin',
  'nicht',
  'kommen',
  'eilen; sich beeilen',
  'gefallen',
  'es macht (keinen) Spaß',
  'plötzich',
  'sehr',
  'sich freuen',
  'was?',
  'schau!/schaut!',
  'wer?'
];

// Lektion 2
List<String> lektion2 = [
  'tandem',
  'sed',
  'apparere',
  'familia',
  'solum',
  'matrona',
  'item',
  'servus',
  'serva',
  'ibi',
  'ridere',
  'cito',
  'appropinquare',
  'iam',
  'procul',
  'salutare',
  'salve!/salvete!',
  'tum',
  'amicus',
  'cessare',
  'timere',
  'nunc',
  'apportare',
  'certa',
  'donum',
  'nam',
  'malum',
  'delectare',
  'equus',
];

List<String> lektion2ExpPPP = [
  '',
  '',
  '',
  'f',
  'Adv.',
  'f',
  '',
  'm',
  'f',
  '',
  '',
  'Adv.',
  '',
  '',
  '',
  '',
  '',
  '',
  'm',
  '',
  '',
  '',
  '',
  'Adv.',
  'n ',
  '',
  'n',
  '',
  'm'
];

List<String> lektion2Exp = [
  '',
  '',
  '',
  'f',
  'Adv.',
  'f',
  '',
  'm',
  'f',
  '',
  '',
  'Adv.',
  '',
  '',
  '',
  '',
  '',
  '',
  'm',
  '',
  '',
  '',
  '',
  'Adv.',
  'n ',
  '',
  'n',
  '',
  'm'
];

List<String> lektion2De = [
  'endlich, schließlich',
  'aber, (je)doch; sondern',
  'erscheinen',
  'die Familie',
  'nur',
  'die Frau',
  'ebenfalls',
  'der Sklave',
  'die Sklavin',
  'dort, da',
  'lachen',
  'schnell',
  'sich nähern',
  'schon',
  'von Weitem; in der Ferne, weit weg',
  '(be)grüßen',
  'sei/seid gegrüßt!',
  'da; dann, darauf; damals',
  'der Freund',
  'zögern',
  '(sich) fürchten',
  'nun, jetzt',
  'herbeitragen',
  'sicher, bestimmt',
  'das Geschenk',
  'denn',
  'der Apfel',
  'erfreuen',
  'das Pferd'
];

// Lektion 3
List<String> lektion3 = [
  'intrare',
  'statim',
  'rogare',
  'unde?',
  'respondere',
  'nuntius',
  'debere',
  'ego/mihi/me',
  'tu/tibi/te',
  'iubere',
  'in',
  'insula',
  'navigare',
  'audire',
  'provincia',
  'administrare',
  'scire',
  'licere/licet',
  'periculum',
  'amare',
  'nihil',
  'vocare',
  'huc',
  'parere',
  'parare',
  'hic',
  'lacrima',
  'tenere'
];
List<String> lektion3Exp = [
  'intro',
  '',
  'rogo',
  '',
  'respondeo',
  'm',
  'debeo',
  '',
  '',
  'iubeo (m.Akk.) ',
  'm. Akk. (prä.) ',
  'f',
  'navigo',
  'audio',
  'f',
  'administro',
  'scio',
  'm.Dat',
  'n',
  'amo',
  '',
  'voco',
  '',
  'pareo',
  'paro',
  '',
  'f',
  'teneo',
];
List<String> lektion3ExpPPP = [
  'intro',
  '',
  'rogo',
  '',
  'respondeo',
  'm',
  'debeo',
  '',
  '',
  'iubeo (m.Akk.) ',
  'm. Akk. (prä.) ',
  'f',
  'navigo',
  'audio',
  'f',
  'administro',
  'scio',
  'm.Dat',
  'n',
  'amo',
  '',
  'voco',
  '',
  'pareo',
  'paro',
  '',
  'f',
  'teneo',
];
List<String> lektion3De = [
  'eintreten',
  'sofort',
  'fragen; bitten',
  'woher?',
  'antworten',
  'der Bote; die Botschaft',
  'müssen; verdanken; schulden',
  'ich/mir/mich',
  'du/dir/dich',
  'befehlen, beauftragen',
  'in, an, auf, nach',
  'die Insel',
  'segeln',
  'hören',
  'die Provinz',
  'verwalten',
  'wissen',
  'es ist möglich; es ist erlaubt, darf',
  'die Gefahr',
  'lieben',
  'nichts',
  'rufen; nennen',
  'hierher',
  'gehorchen',
  'bereiten; vorhaben',
  'hier',
  'die Träne',
  'halten',
];

// Lektion 4
List<String> lektion4 = [
  'homo',
  'sedere',
  'diu',
  'spectaculum',
  'consul',
  'avus',
  'modo',
  'autem',
  'videre',
  'imperator',
  'ave!',
  'populus',
  'verbum',
  'simulacrum',
  'deus',
  'rex',
  'regina',
  'dea',
  'amor',
  'spectare',
  'initium',
  'signum',
  'dare',
  'incitare',
  'ardor',
  'clamor',
  'furor',
  'neque'
];

List<String> lektion4ExpPPP = [
  'hominis m',
  'sedeo sedi sessum',
  'adv.',
  'spectaculi n',
  'consulis m',
  'avi m',
  '',
  'nachgestellt',
  'video vidi visum',
  'imperatoris m',
  '',
  'populi m',
  'verbi n',
  'simulacri n',
  'dei m ',
  'regis m',
  'reginae  f',
  'deae f',
  'amoris m',
  'specto spectavi spectatum ',
  'initii n ',
  'signi n ',
  'do dedi datum',
  'incito incitavi incitatum',
  'ardoris m ',
  'clamoris m',
  'furoris m',
  ''
];

List<String> lektion4Exp = [
  'hominis m',
  'sedeo',
  'adv.',
  'spectaculi n',
  'consulis m',
  'avi m',
  '',
  'nachgestellt',
  'video',
  'imperatoris m',
  '',
  'populi m',
  'verbi n',
  'simulacri n',
  'dei m ',
  'regis m',
  'reginae  f',
  'deae f',
  'amoris m',
  'specto ',
  'initii n ',
  'signi n ',
  'do',
  'incito',
  'ardoris m ',
  'clamoris m',
  'furoris m',
  ''
];

List<String> lektion4De = [
  'der Mensch',
  '(da) sitzen',
  'lange',
  'das Schauspiel; die Veranstaltung',
  'der Konsul',
  'der Großvater',
  'gerade; nur',
  'aber, (je)doch',
  'sehen',
  'der Kaiser; der Feldherr',
  'sei gegrüßt!',
  'das Volk; das Publikum',
  'das Wort',
  'das Bild',
  'der Gott',
  'der König',
  'die Königin',
  'die Göttin',
  'die Liebe',
  '(an) schauen',
  'der Anfang, der Beginn',
  'das Zeichen',
  'geben',
  'antreiben',
  'das Temperament; die Hitze',
  'der Schrei',
  'das Toben',
  'und ... nicht; auch ... nicht; aber ... nicht'
];

// Lektion 5

List<String> lektion5 = [
  'ante',
  'ludere',
  'semper',
  'pater',
  'patronus',
  'causa',
  'dicere',
  'forum',
  'dum',
  'epistula',
  'legere',
  'nox',
  'ludex',
  'dormire',
  'invadere',
  'domina',
  'sumere',
  'decedere',
  'accurrere',
  'dominus',
  'fur',
  'quaerere',
  'reus',
  'si',
  'fuga',
  'petere',
  'fugam petere',
  'solere',
  'orator',
  'plaudere'
];

List<String> lektion5ExpPPP = [
  'm. Akk',
  'ludo',
  'adv.',
  'patris m',
  'patroni m',
  'causae f',
  'dico',
  'fori n',
  'Subj. m.Präs',
  'epistulae f',
  'lego',
  'noctis f',
  'iudecis m',
  'dormio',
  'invado',
  'dominae f',
  'sumo',
  'decedo',
  'accurro',
  'domini m',
  'furis m',
  'quaero',
  'rei m',
  'Subj.',
  'fugae f',
  'peto',
  'soleo',
  'oratoris m',
  'plaudo'
];
List<String> lektion5Exp = [
  'm. Akk',
  'ludo',
  'adv.',
  'patris m',
  'patroni m',
  'causae f',
  'dico',
  'fori n',
  'Subj. m.Präs',
  'epistulae f',
  'lego',
  'noctis f',
  'iudecis m',
  'dormio',
  'invado',
  'dominae f',
  'sumo',
  'decedo',
  'accurro',
  'domini m',
  'furis m',
  'quaero',
  'rei m',
  'Subj.',
  'fugae f',
  'peto',
  'soleo',
  'oratoris m',
  'plaudo'
];

List<String> lektion5De = [
  'vor',
  'spielen',
  'immer',
  'der Vater',
  'der Anwalt, der Schirmherr',
  'der Grund; der Prozess',
  'sagen, sprechen',
  'das Forum; der Marktplatz',
  'während',
  'der Brief',
  'lesen',
  'die Nacht',
  'der Richter',
  'schlafen',
  'eindringen, angreifen',
  'die (Haus-)Herrin',
  'nehmen',
  'weggehen',
  'herbeilaufen',
  'der (Haus-)Herr',
  'der Dieb',
  'suchen, fragen',
  'der Angeklagte',
  'wenn, falls',
  'die Flucht',
  'bitten, angreifen, aufsuchen',
  'die Flucht ergreifen',
  'gewohnt sein',
  'der Redner',
  'Beifall klatschen'
];

//Lektion 6
List<String> lektion6 = [
  'navis',
  'laetus',
  'ad',
  'terra',
  'novus',
  'alienus',
  'maestus',
  'ventus',
  'secundus',
  'nauta',
  'solus',
  'magnus',
  'mater',
  'pirata',
  'arma',
  'abducere',
  'femina',
  'defendere',
  'ubique',
  'orare',
  'bonus',
  'auxilium',
  'multi',
  'multum',
  'pugnare',
  'superare',
  'alius',
  'alii ... alii ...',
  'necare',
  'praecipitare'
];
List<String> lektion6ExpPPP = [
  'navis f',
  'laeta, laetum',
  'm.Akk',
  'terrae f',
  'nova, novum',
  'aliena, alienum',
  'maesta, maestum',
  'venti m',
  'secunda, secundum',
  'nautae m',
  'sola, solum',
  'magna magnum ',
  'matris f',
  'piratae m',
  'armorum n',
  'abduco',
  'feminae f',
  'defendo',
  '',
  'oro',
  'bona, bonum',
  'auxilii n',
  'multae, multa',
  'Adv.',
  'pugno',
  'supero',
  'alia, aliud',
  '',
  'neco',
  'praecipito',
  ''
];
List<String> lektion6Exp = [
  'navis f',
  'laeta, laetum',
  'm.Akk',
  'terrae f',
  'nova, novum',
  'aliena, alienum',
  'maesta, maestum',
  'venti m',
  'secunda, secundum',
  'nautae m',
  'sola, solum',
  'magna magnum ',
  'matris f',
  'piratae m',
  'armorum n',
  'abduco',
  'feminae f',
  'defendo',
  '',
  'oro',
  'bona, bonum',
  'auxilii n',
  'multae, multa',
  'Adv.',
  'pugno',
  'supero',
  'alia, aliud',
  '',
  'neco',
  'praecipito',
  ''
];

List<String> lektion6De = [
  'das Schiff',
  'froh',
  'zu; zu ... hin; an; bei',
  'die Erde; das Land',
  'neu',
  'fremd',
  'traurig',
  'der Wind',
  'der zweite, der folgende; günstig',
  'der Seemann',
  'allein, einzig',
  'groß',
  'die Mutter',
  'der Pirat',
  'die Waffen',
  'wegführen',
  'die Frau',
  'verteidigen; abwehren',
  'überall',
  'bitten; beten',
  'gut, tüchtig',
  'die Hilfe',
  'viele',
  'viel',
  'kämpfen',
  '(be)siegen; übertreffen',
  'ein anderer',
  'die einen ... (die) andere(n)',
  'töten',
  'hinabstürzen',
  ''
];

//Lektion 7
List<String> lektion7 = [
  'cum',
  'in',
  'ambulare',
  'icundus',
  'itaque',
  'voluptas',
  'num?',
  'aqua',
  'currere',
  'primo',
  'deinde',
  'manere',
  'post',
  'oculus',
  'sine',
  'mens',
  'anima',
  'continere',
  'animam continere',
  'unus',
  'e/ex',
  'medicus',
  'nonne?',
  'iterum',
  '-ne?',
  'accedere',
  'portare',
  'mortuus'
];

List<String> lektion7ExpPPP = [
  'm.Abl',
  'm.Abl',
  'ambulo',
  'iucunda, iucundum',
  '',
  'voluptatis f',
  '',
  'aquae f',
  'curro',
  '',
  '',
  'maneo',
  'adv.',
  'oculi m',
  'm.Abl',
  'mentis f',
  'animae f',
  'contineo',
  '',
  'una, unum',
  'm. Abl',
  'medici m',
  '',
  '',
  'angehängt',
  'accedo',
  'porto',
  'mortua, mortuum',
];

List<String> lektion7Exp = [
  'm.Abl',
  'm.Abl',
  'ambulo',
  'iucunda, iucundum',
  '',
  'voluptatis f',
  '',
  'aquae f',
  'curro',
  '',
  '',
  'maneo',
  'adv.',
  'oculi m',
  'm.Abl',
  'mentis f',
  'animae f',
  'contineo',
  '',
  'una, unum',
  'm. Abl',
  'medici m',
  '',
  '',
  'angehängt',
  'accedo',
  'porto',
  'mortua, mortuum',
];
List<String> lektion7De = [
  'mit',
  'in, an, auf',
  '(spazieren) gehen',
  'angenehm, liebenswürdig',
  'deshalb',
  'das Vergnügen',
  'etwa?',
  'das Wasser',
  'laufen',
  'zuerst',
  'dann, darauf',
  'bleiben',
  'später; danach',
  'das Auge',
  'ohne',
  'der Geist',
  'der Atem; sie Seele; das Leben',
  'halten',
  'den Atem/die Luft anhalten',
  'ein; ein einziger',
  'aus',
  'der Arzt',
  'denn nicht?; etwa nicht?',
  'wieder',
  'Fragesignal (das nicht übersetzt wird)',
  'herantreten',
  'tragen; bringen',
  'tot; gestorben',
];

// Lektion 23
List<String> lektion23 = [
  'pauci',
  'divitiae',
  'abundare',
  'maximus',
  'pars',
  'miseria',
  'cum',
  'anitquus',
  'lex',
  'pessimus',
  'tribunus',
  'vetare',
  'confirmare',
  'tunc',
  'plebs',
  'necessarius',
  'pax',
  'otium',
  'deponere',
  'fama',
  'officium',
  'praestare',
  'interficere',
  'recusare',
  'scelus',
  'turpis',
  'occidere',
  'adversus'
];

List<String> lektion23ExpPPP = [
  'paucae, pauca',
  'divitiarum f',
  'm. Abl',
  'maxima, maximum',
  'partis f',
  'miseriae f',
  'Subjunktion; m. Konj.',
  'antiqua, antiquum',
  'legis f',
  'pessima, pessimum',
  'tribuni m',
  'veto, vetui, vetitum',
  'confirmo, confirmavi, confirmatum',
  '',
  'plebis f',
  'necessarius, necessarium',
  'pacis f',
  'otii n',
  'depono, deposui, depositum',
  'famae f',
  'officii n',
  'praesto, praestiti, - ',
  'interficio, interfeci, interfectum',
  'recuso, recusavi, recusatum',
  'sceleris n',
  'turpis, turpe',
  'occido, occidi, occisum',
  'm. Akk'
];

List<String> lektion23Exp = [
  'paucae, pauca',
  'divitiarum f',
  'm. Abl',
  'maxima, maximum',
  'partis f',
  'miseriae f',
  'Subjunktion; m. Konj.',
  'antiqua, antiquum',
  'legis f',
  'pessima, pessimum',
  'tribuni m',
  'veto, vetui, vetitum',
  'confirmo',
  '',
  'plebis f',
  'necessarius, necessarium',
  'pacis f',
  'otii n',
  'depono',
  'famae f',
  'officii n',
  'praesto',
  'interficio',
  'recuso, recusavi, recusatum',
  'sceleris n',
  'turpis, turpe',
  'occido',
  'm. Akk'
];
List<String> lektion23De = [
  'wenig, nur wenige',
  'der Reichtum',
  'im Überfluss haben',
  'der größte; sehr groß',
  'der Teil; die Seite; die Richtung',
  'das Elend; das Unglück',
  'als, nachdem; weil; obwohl',
  'alt',
  'das Gesetz',
  'der schlechteste; der schlimmste; sehr schlecht, sehr schlimm',
  'der (Militär-,Volks-) Tribun',
  'verbiegen',
  'bekräftigen; ermutigen',
  'da(mals), in d(ies)em Augenblick',
  'die Plebejer; das Volk',
  'notwendig; der Verwandte; der Freund; der Klient',
  'der Frieden',
  'die Ruhe; die freie Zeit',
  'niederlegen; aufgeben',
  'das Gerede; das Gerücht',
  'der Dienst; die Pflicht',
  'leisten; übertreffen',
  'töten',
  'verweigern; sich weigern',
  'das Verbrechen',
  'schändlich; hässlich',
  'töten',
  'gegen; gegenüber'
];
// Lektion 24 Block 1+2 (Vorübergend)

// TO-DO: Am 27.09.2023 wieder rausnehmen!
List<String> lektion24B1 = [
  'quaerere ab/ex',
  'qui?',
  'abesse',
  'adesse',
  'imperium',
  'consultum',
  'pellere',
  'iniuria',
  'censere',
  'conficere',
  'dimittere',
  'interesse',
  'minae',
  'iactare',
  'resistere',
  'explere'
];

List<String> lektion24B1ExpPPP = [
  'm. Abl, quaereo quaerui, quaeretum',
  'quae, quod',
  'absum, afui',
  'adsum adfui/affui',
  'imperii n',
  'consulti n',
  'pello, pepuli, pulsum',
  'iniuriae f',
  'censeo, censui, censum',
  'conficio, confeci, confectum',
  'dimitto, dimisi, dimissum',
  'intersum, interfui (m. Dat)',
  'minarum f',
  'iacto, iactavi, iactatum',
  'resisto, resiti, -',
  'expleo, explevi, expletum',
];

List<String> lektion24B1Exp = [
  'm. Abl, quaereo',
  'quae, quod',
  'absum',
  'adsum',
  'imperii n',
  'consulti n',
  'pello',
  'iniuriae f',
  'censeo',
  'conficio',
  'dimitto',
  'intersum',
  'minarum f',
  'iacto',
  'resisto',
  'expleo',
];
List<String> lektion24B1De = [
  '(jmdn.) fragen',
  'welcher, welche, welches?',
  'abwesend sein',
  'anwesend sein; helfen',
  'der Befehl; die Herrschaft; das Reich',
  'der Beschluss',
  'schlagen, stoßen; vertreiben',
  'das Unrecht; die Ungerechtigkeit',
  'schätzen; der Ansicht sein',
  'beenden; durchführen',
  'wegschicken',
  'teilnehmen',
  'die Drohungen',
  'schleudern, äußern',
  'Wiederstand leisten',
  '(an-,aus-,er-)füllen'
];

// Lektion 24 vollständig

List<String> lektion24 = [
  'quaerere ab/ex',
  'qui?',
  'abesse',
  'adesse',
  'imperium',
  'consultum',
  'pellere',
  'iniuria',
  'censere',
  'conficere',
  'dimittere',
  'interesse',
  'minae',
  'iactare',
  'resistere',
  'explere',
  'clam',
  'flumen',
  'sol',
  'occidere',
  'eo',
  'occultus',
  'ripa',
  'posse',
  'accidere',
  'iuvenis',
  'magnitudo',
  'plerique',
  'quo?',
  'iacere'
];

List<String> lektion24ExpPPP = [
  'm. Abl, quaereo quaerui, quaeretum',
  'quae, quod',
  'absum, afui',
  'adsum adfui/affui',
  'imperii n',
  'consulti n',
  'pello, pepuli, pulsum',
  'iniuriae f',
  'censeo, censui, censum',
  'conficio, confeci, confectum',
  'dimitto, dimisi, dimissum',
  'intersum, interfui (m. Dat)',
  'minarum f',
  'iacto, iactavi, iactatum',
  'resisto, resiti, -',
  'expleo, explevi, expletum',
  'Adv.',
  'fluminis n',
  'solis m',
  'occido, occidi, -',
  '',
  'occulta, occultum',
  'ripae f',
  'possum, potui',
  'accidit, accidit, -',
  'iuvenis m',
  'magnitudinis f',
  'pleraeque, pleraque',
  '',
  'iacio, ieci, iactum'
];

List<String> lektion24Exp = [
  'm. Abl, quaereo',
  'quae, quod',
  'absum',
  'adsum',
  'imperii n',
  'consulti n',
  'pello',
  'iniuriae f',
  'censeo',
  'conficio',
  'dimitto',
  'intersum, interfui (m. Dat)',
  'minarum f',
  'iacto',
  'resisto',
  'expleo',
  'Adv.',
  'fluminis n',
  'solis m',
  'occido',
  '',
  'occulta',
  'ripae f',
  'possum',
  'accidit',
  'iuvenis m',
  'magnitudinis f',
  'pleraeque, pleraque',
  '',
  'iacio'
];

List<String> lektion24De = [
  '(jmdn.) fragen',
  'welcher, welche, welches?',
  'abwesend sein',
  'anwesend sein; helfen',
  'der Befehl; die Herrschaft; das Reich',
  'der Beschluss',
  'schlagen, stoßen; vertreiben',
  'das Unrecht; die Ungerechtigkeit',
  'schätzen; der Ansicht sein',
  'beenden; durchführen',
  'wegschicken',
  'teilnehmen',
  'die Drohungen',
  'schleudern, äußern',
  'Wiederstand leisten',
  '(an-,aus-,er-)füllen',
  'heimlich',
  'der Fluss',
  'die Sonne',
  'untergehen; unterkommen',
  'dorthin',
  'heimlich, geheim',
  'das Ufer',
  'können',
  'sich ereignen, zustoßen',
  'der junge Mann',
  'die Größe',
  'die meisten; sehr viele',
  'wohin?',
  'werfen'
];
